# Makefile MinGW

SHELL := cmd.exe
MAKE  := "$(MAKE)"

CPPFLAGS += -Dmain=SDL_main

LDFLAGS := -lmingw32 -mwindows -mconsole -lSDL2main $(LDFLAGS)
LDFLAGS += -lopengl32
LDFLAGS += -lglew32

DLL = /MinGW/mingw32/bin
DLLS += SDL2.dll
DLLS += glew32.dll

TARGET := $(TARGET).exe
